version: '3'

services:
  mysql:
    build:
      context: ./data-init
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: boxprint
      MYSQL_USER: dockertest
      MYSQL_PASSWORD: dockertest_password

  magento:
    build: ./magento
    ports:
      - "80:80"
    environment:
      MAGENTO_DB_HOST: mysql
      MAGENTO_DB_NAME: boxprint
      MAGENTO_DB_USER: dockertest
      MAGENTO_DB_PASSWORD: dockertest_password
    depends_on:
      - mysql
