version: '3'

services:
  mysql:
    build:
      context: ./data-init
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fantasy7&
      MYSQL_DATABASE: boxprint
      MYSQL_USER: dockertest
      MYSQL_PASSWORD: dockertest_password

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  magento:
    build: ./magento
    ports:
      - "80:80"
    environment:
      MAGENTO_DB_HOST: mysql
      MAGENTO_DB_NAME: boxprint
      MAGENTO_DB_USER: dockertest
      MAGENTO_DB_PASSWORD: dockertest_password
      MAGENTO_DOMAIN: boxoprint.neotiq.net
      MAGENTO_ELASTICSEARCH_HOST: elasticsearch
    depends_on:
      - mysql
      - elasticsearch
