version: '3'

services:
  mysql:
    build:
      context: ./data-init
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fantasy7&
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  magento:
    build: ./magento
    volumes:
      - fe_build:/var/www/html/pub/build
    ports:
      - "80:80"
      - "443:443"
    environment:
      MAGENTO_DB_HOST: mysql
      MAGENTO_DB_NAME: ${DB_NAME}
      MAGENTO_DB_USER: ${DB_USER}
      MAGENTO_DB_PASSWORD: ${DB_PASSWORD}
      MAGENTO_DOMAIN: ${BACKEND_HOST}
      MAGENTO_ELASTICSEARCH_HOST: elasticsearch
    depends_on:
      - mysql
      - elasticsearch
  backend:
    build:
      context: ./boxtool/src
      args:
        BACKEND_DB_NAME: ${DB_NAME}
        BACKEND_DB_USER: ${DB_USER}
        BACKEND_DB_PASSWORD: ${DB_PASSWORD}
        BACKEND_HOST: ${BACKEND_HOST}
        BACKEND_DB_HOST: mysql
    ports:
      - "8082:8082"  
    depends_on:
        - mysql
  frontend:
    build:
      context: ./boxtool/ui
      args: 
        BACKEND_HOST: ${BACKEND_HOST}
    volumes:
      - fe_build:/var/www/boxtool/ui/build
    depends_on:
      - mysql
      - backend
      - magento
volumes:
  fe_build:        

