version: '3'

variables:
  &db_name boxprint
  &db_user boxo
  &db_password boxotestPassword

services:
  mysql:
    build:
      context: ./data-init
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fantasy7&
      MYSQL_DATABASE: *db_name
      MYSQL_USER: *db_user
      MYSQL_PASSWORD: *db_password

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  magento:
    build: ./magento
    ports:
      - "80:80"
    environment:
      MAGENTO_DB_HOST: mysql
      MAGENTO_DB_NAME: *db_name
      MAGENTO_DB_USER: *db_user
      MAGENTO_DB_PASSWORD: *db_password
      MAGENTO_DOMAIN: boxoprint.neotiq.net
      MAGENTO_ELASTICSEARCH_HOST: elasticsearch
    depends_on:
      - mysql
      - elasticsearch
  backend:
    build:
      context: ./boxtool/src
      ports:
        - "8082:8082"
      environment:
        BACKEND_DB_HOST: mysql
        BACKEND_DB_NAME: *db_name
        BACKEND_DB_USER: *db_user
        BACKEND_DB_PASSWORD: *db_password
      depends_on:
        - mysql
  frontend:
    build:
      context: ./boxtool/ui
      # environment:
      #   BACKEND_DB_HOST: mysql
      #   BACKEND_DB_NAME: *db_name
      #   BACKEND_DB_USER: *db_user
      #   BACKEND_DB_PASSWORD: *db_password
      depends_on:
        - mysql
        - backend
        - magento
        

