<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\Sales\Block\Order\Items $block */
?>
<div class="table-wrapper order-items">
    <table style="table-layout: auto;" class="data table table-order-items" id="my-orders-table" summary="<?= $block->escapeHtml(__('Items Ordered')) ?>">
        <caption class="table-caption"><?= $block->escapeHtml(__('Items Ordered')) ?></caption>
        <tr>
            <th class="col name" style="width: 25%"><?= $block->escapeHtml(__('Product Name')) ?></th>
            <th class="col detail" style="width: 75%"><?= $block->escapeHtml(__('Detail')) ?></th>
        </tr>
        <?php $items = $block->getItems(); ?>
        <?php $giftMessage = ''?>
        <?php foreach ($items as $item) :
            if ($item->getParentItem()) :
                continue;
            endif;
            ?>
            <tbody>
            <?= $block->getItemHtml($item) ?>
            <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)->isMessagesAllowed('order_item', $item) && $item->getGiftMessageId()) : ?>
                <?php $giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)->getGiftMessageForEntity($item); ?>
                <tr>
                    <td class="col options" colspan="5">
                        <a href="#"
                           id="order-item-gift-message-link-<?= (int) $item->getId() ?>"
                           class="action show"
                           aria-controls="order-item-gift-message-<?= (int) $item->getId() ?>"
                           data-item-id="<?= (int) $item->getId() ?>">
                            <?= $block->escapeHtml(__('Gift Message')) ?>
                        </a>
                        <?php $giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)->getGiftMessageForEntity($item); ?>
                        <div class="order-gift-message" id="order-item-gift-message-<?= (int) $item->getId() ?>" role="region" aria-expanded="false" tabindex="-1">
                            <a href="#"
                               title="<?= $block->escapeHtml(__('Close')) ?>"
                               aria-controls="order-item-gift-message-<?= (int) $item->getId() ?>"
                               data-item-id="<?= (int) $item->getId() ?>"
                               class="action close">
                                <?= $block->escapeHtml(__('Close')) ?>
                            </a>
                            <dl class="item-options">
                                <dt class="item-sender"><strong class="label"><?= $block->escapeHtml(__('From')) ?></strong><?= $block->escapeHtml($giftMessage->getSender()) ?></dt>
                                <dt class="item-recipient"><strong class="label"><?= $block->escapeHtml(__('To')) ?></strong><?= $block->escapeHtml($giftMessage->getRecipient()) ?></dt>
                                <dd class="item-message"><?= /* @noEscape */ $this->helper(\Magento\GiftMessage\Helper\Message::class)->getEscapedGiftMessage($item) ?></dd>
                            </dl>
                        </div>
                    </td>
                </tr>
            <?php endif ?>
            </tbody>
        <?php endforeach; ?>
    </table>
    <table class="data table table-order-total" style="width: 50%;float: right;">
        <?= $block->getChildHtml('order_totals') ?>
    </table>
</div>
<?php if ($giftMessage) : ?>
    <script type="text/x-magento-init">
    {
        "a.action.show, a.action.close": {
            "giftMessage": {}
        }
    }
</script>
<?php endif; ?>
