<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
$neotiqHelperData = $this->helper('Neotiq\Neotiq\Helper\Data');
$neotiqBoxprintHelperData = $this->helper('Neotiq\Boxprint\Helper\Data');
?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="col name" data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>">
        <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
        <div class="item-info">
            <?php if ($_options = $block->getItemOptions()) : ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                        <?php if (!$block->getPrintStatus()) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                    <?= $block->escapeHtml($_formatedOptionValue['full_view'], ['a']) ?>
                                <?php else : ?>
                                    <?=$block->escapeHtml($_formatedOptionValue['value'], ['a']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php else : ?>
                            <dd>
                                <?= /* @noEscape */ nl2br($block->escapeHtml($_option['print_value'] ?? $_option['value'])) ?>
                            </dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addtInfoBlock) : ?>
                <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif; ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>
            <?php if($_item->getData('mdq_workspaceid')):?>
                <?php
                $workspace = $neotiqBoxprintHelperData->getWorkspaceById($_item->getData('mdq_workspaceid'));
                ?>
                <?php if($workspace):?>
                    <?php $image_src = $neotiqBoxprintHelperData->getBaseUrlByType(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).\Neotiq\Boxprint\Helper\Data::BOX_SAVE_PATH.'/'.$workspace->getImage();?>
                    <image src="<?php echo $image_src ?>" alt="<?php echo $workspace->getLabel();?>" />
                <?php endif;?>
            <?php endif;?>
        </div>
    </td>
    <td class="col sku" data-th="<?= $block->escapeHtmlAttr(__('SKU')) ?>"><?= /* @noEscape */ $block->prepareSku($block->getSku()) ?></td>
    <td class="col price" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
        <?php if ($block->getItem()->getQtyOrdered() > 0) : ?>
                <span><?= (float) $block->getItem()->getQtyOrdered() ?></span>
        <?php endif; ?>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
</tr>
