<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
$_product =$_item->getProduct();
$_product_url_workspace = $_product->getProductUrl();
if($_item->getData('mdq_workspaceid')){
    $_product_url_workspace = $_product->getProductUrl().'?boxo='.$_item->getData('mdq_workspaceid');
}
?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>" class="order-item">
    <td class="col name" data-th="<?= $block->escapeHtml(__('Product Name')) ?>">
        <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()): ?>
            <dl class="item-options">
                <?php foreach ($_options as $_option): ?>
                    <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                    <?php if (!$block->getPrintStatus()): ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dd<?= (isset($_formatedOptionValue['full_view']) ? ' class="tooltip wrapper"' : '') ?>>
                            <?= $block->escapeHtml($_formatedOptionValue['value'], ['a']) ?>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <div class="tooltip content">
                                    <dl class="item options">
                                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                        <dd><?= $block->escapeHtml($_formatedOptionValue['full_view']) ?></dd>
                                    </dl>
                                </div>
                            <?php endif; ?>
                        </dd>
                    <?php else: ?>
                        <?php $optionValue = isset($_option['print_value']) ? $_option['print_value'] : $_option['value'] ?>
                        <dd><?= $block->escapeHtml($optionValue) ?></dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock): ?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?= $block->escapeHtml(__('SKU')) ?>">
        <?= /* @noEscape */ $block->prepareSku($block->getSku()) ?>
    </td>
    <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <ul class="items-qty">
            <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
                <li class="item">
                    <span class="title"><?= $block->escapeHtml(__('Ordered')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyOrdered() ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyShipped() > 0): ?>
                <li class="item">
                    <span class="title"><?= $block->escapeHtml(__('Shipped')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyShipped() ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
                <li class="item">
                    <span class="title"><?= $block->escapeHtml(__('Canceled')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyCanceled() ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
                <li class="item">
                    <span class="title"><?= $block->escapeHtml(__('Refunded')) ?></span>
                    <span class="content"><?= (float) $block->getItem()->getQtyRefunded() ?></span>
                </li>
            <?php endif; ?>
        </ul>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
        <?php if($_item->getData('mdq_workspaceid')):?>
            <div class="product-boxoprint"><div class="view-all-<?php echo $_item->getId();?>"><?php echo __('Des détails')?></div></div>
            <div class="product-boxoprint-edit"><div class="edit-<?php echo $_item->getId();?>"><a target="_blank" href="<?php echo $_product_url_workspace ?>"><?php echo __('Ajouter')?></a></div></div>
        <?php endif;?>
    </td>
</tr>
<?php if($_item->getData('mdq_workspaceid')):?>
<script type="text/javascript">
    require(['jquery','Magento_Ui/js/modal/confirm','domReady!','mage/translate','mage/cookies'], function($, confirmation){
        $('.product-boxoprint .view-all-<?php echo $_item->getId();?>').click(function(e){
            e.preventDefault();
            var box_view_all = '<?php echo $this->getUrl('mdqboxprint/index/info')?>';
            var productId = '<?php echo $_item->getData('product_id')?>';
            var box_workspace_id = '<?php echo $_item->getData('mdq_workspaceid')?>';
            $.ajax({
                type: "POST",
                url: box_view_all,
                data: {
                    productId:productId,
                    workspaceId:box_workspace_id
                },
                showLoader: true,
                dataType: 'json',
                success: function(responseData)
                {
                    if(responseData.mdq_boxprint_info!='') {
                        confirmation({
                            title: $.mage.__('Des détails'),
                            content: responseData.mdq_boxprint_info,
                            buttons: [],
                            modalClass: 'boxprint-popup-viewall',
                        });
                    }
                }
            });
        });
    });
</script>
<?php endif;?>
